#!/usr/bin/env bash

slyfile='Slyfile'

# Colors
red=31
green=32
yellow=33
cyan=36
bold=$(tput smul)
reset=$(tput sgr0)

sly_prepend() {
  color="${2-$yellow}"
  prefix="$(printf "\e[%sm%s\e[m" "$color" "$(printf "%-3s | " "${1-SLY}")")"
  while IFS= read line; do
    echo -e "${prefix}${line}"
  done
}

sly_error() {
  \printf '\a%s\n' "$1" | sly_prepend "SLY ERROR" $red >&2
}

sly_has_slyfile() {
  [ -f "$slyfile" ]
}

sly() {
  if sly_has_slyfile; then
    has_short_fn="$(grep -E "^${1}\s*\(\)" "$slyfile")"
    has_long_fn="$(grep -E "^function\s+${1}" "$slyfile")"
    if [ -z "$has_short_fn" ] && [ -z "$has_long_fn" ]; then
      sly_error "$slyfile has no function called ${bold}${1}${reset}"
      exit 1
    fi

    source "$slyfile"
  else
    sly_error "$slyfile not found"
    sly_error "Create one with ${bold}sly --init${reset}"
    exit 1
  fi

  if [ -z "$(command -v $1)" ]; then
    sly_error "$slyfile has no function called ${bold}${1}${reset}"
    exit 1
  fi

  echo "Executing function: ${bold}${1}${reset}" | sly_prepend
  declare -f  $1 | sly_prepend

  # $@ 2>&1 | sly_prepend "SLY"
  $@
}

sly_init() {
  if sly_has_slyfile; then
    sly_error "$slyfile already exists"
    exit 1
  fi

  cat << SLY > $slyfile
# -*- mode: sh; -*- vim: set ft=sh:
#
### $slyfile - used by sly
### https://github.com/richarddewit/sly
#
# Add your functions below. They may contain any Bash code.
# Example:
#
#   ping_home() {
#     ping -c \${1-5} 127.0.0.1
#     screenfetch
#   }
#
# Then run it with \`sly ping_home 10\` to do 10 pings to localhost and
# run \`screenfetch\` afterwards.


SLY
  echo "Sly initialised into $(pwd)/$slyfile" | sly_prepend
  echo "Go add some functions to the $slyfile!" | sly_prepend
  exit 0
}

[ -z "$1" ] && sly_error "Missing argument COMMAND" && exit 1
if [ "$1" == "--help" ]; then
  echo "Sly - a CLI tool utilizing plain Bash functions" | sly_prepend
  echo "~~~" | sly_prepend
  echo "" | sly_prepend
  echo "Usage: sly COMMAND [ARGUMENTS]" | sly_prepend
  echo "Options:" | sly_prepend
  echo "    --help     Show this message" | sly_prepend
  echo "    --init     Initialize an empty ${slyfile}" | sly_prepend
  exit 0
fi

[ "$1" == "--init" ] && sly_init

(sly $@)
