#!/usr/bin/env bash

# Variables
slyfile='Slyfile'

## Colors
red=31
yellow=33
bold=$(tput smul)
reset=$(tput sgr0)


# Utils
sly_print_color() {
  printf "\e[%sm%s\e[m" "$1" "$2"
}

sly_prepend() {
  color="${2-$yellow}"
  prefix="$(sly_print_color "$color" "$(printf "%-3s | " "${1-SLY}")")"
  while IFS= read -r line; do
    >&2 echo -e "${prefix}${line}"
  done
}

sly_error() {
  printf '\a%s\n' "$1" | sly_prepend "SLY ERROR" $red >&2
}

sly_has_slyfile() {
  [ -f "$slyfile" ]
}

sly_no_slyfile() {
  sly_error "$slyfile not found"
  sly_error "Create one with ${bold}sly --init${reset}"
  exit 1
}

sly_available_functions() {
  if sly_has_slyfile; then
    # shellcheck source=/dev/null
    source "$slyfile"
    declare -F | awk '{print $NF}' | sort | grep -Ev "^sly_"
  else
    sly_no_slyfile
  fi
}


# Commands
sly_exec() {
  if sly_has_slyfile; then
    has_short_fn="$(grep -E "^${1}\s*\(\)" "$slyfile")"
    has_long_fn="$(grep -E "^function\s+${1}" "$slyfile")"
    if [ -z "$has_short_fn" ] && [ -z "$has_long_fn" ]; then
      sly_error "$slyfile has no function called ${bold}${1}${reset}"
      exit 1
    fi

    # shellcheck source=/dev/null
    source "$slyfile"
  else
    sly_no_slyfile
  fi

  if [ -z "$(command -v "$1")" ]; then
    sly_error "$slyfile has no function called ${bold}${1}${reset}"
    exit 1
  fi

  echo "Executing function: ${bold}${1}${reset}" | sly_prepend
  declare -f "$1" | sly_prepend

  # $@ 2>&1 | sly_prepend "SLY"
  "$@"
}

sly_help() {
  cat << SLY | sly_prepend
   ::     .
   mMs/:-oy:
   dMMMMMMh.
  :MMMMMMMy\`
  hMMMMMMN//+///--::-:.---..
  dMMMMMMMMMMMMMMMMMMmmMMMMNmdys+/:-..-+
  dMMMMMMMM $(sly_print_color "$yellow" "SLY") MMMMMMMNNMMMMMMMMMMMNNm/
  -dMMMMMMMMMMMMMMMMMMMh.+sydmMMMMNmh/.
   \`/hMMmMMMMmmmMMMNMMMN-   \`..--..\`
     oMh\`+MM+\`\`\`ohNdohNMNy/\`
    \`md\`  mN     \`Nd\` \`.-hM/
   :yN.   Nm   .+hN.     \`mm\`
  .oo:  /mm/   \`::/      /s+

SLY
  echo "Sly - a CLI tool utilizing plain Bash functions" | sly_prepend
  echo "~~~" | sly_prepend
  echo "" | sly_prepend
  echo "Usage: sly COMMAND [ARGUMENTS]" | sly_prepend
  echo "Options:" | sly_prepend
  echo "    -h --help     Show this message" | sly_prepend
  echo "    -i --init     Initialize an empty ${slyfile}" | sly_prepend
  echo "    -l --list     List available commands" | sly_prepend
  exit 0
}

sly_init() {
  if sly_has_slyfile; then
    sly_error "$slyfile already exists"
    exit 1
  fi

  cat << SLY > $slyfile
#!/usr/bin/env bash
#
### $slyfile - used by sly
### https://github.com/richarddewit/sly
#
# Compose your functions here. They may contain any Bash code.

example() {
  # To run this example, try these commands for different output:
  #   \`sly example\`
  #   \`sly example 2 5\`
  #   \`sly example 3 3\`
  width=\${1-12}
  length=\${2-5}
  area=\$((width * length))
  echo "Area is: \$area (\${width} x \${length})"
  [ "\$width" == "\$length" ] && echo "It's a square"
  echo "And the current directory is: \$(pwd)"
  echo "Calling 'uname -a':"
  uname -a
  # Remember, it's just plain bash. No magic.
}
SLY
  echo "Sly initialised into $(pwd)/$slyfile" | sly_prepend
  echo "Go add some functions to the $slyfile!" | sly_prepend
  exit 0
}

sly_list() {
  echo "Available commands:" | sly_prepend
  echo "" | sly_prepend
  sly_available_functions | sly_prepend
  exit 0
}


# Execution
[ -z "$1" ] && sly_error "Missing argument COMMAND" && exit 1
[[ "$1" =~ ^sly_ ]] && sly_error "The sly_ prefix is reserved for sly internal functions" && exit 1
[[ "$1" =~ ^(-h|--help)$ ]] && sly_help
[[ "$1" =~ ^(-i|--init)$ ]] && sly_init
[[ "$1" =~ ^(-l|--list)$ ]] && sly_list

(sly_exec "$@")
